### ISSUE TITLE
[공통] CI/CD를 젠킨스에서 workflow.yml로 이관하고, 기존 workflow를 삭제한다.

### ISSUE THREAD

**Issue by sihyung92** [woowacourse-teams/2021-jujeol-jujeol#602]
### 설명
젠킨스에서 깃헙액션으로 CI/CD를 이관하고, 기존 workflow를 삭제한다.
삭제한 workflow.yml은 해당 이슈에 첨부한다.

### 진행상황
- [x] workflow.yml 구성
- [x] 삭제되는 기존 파일 이슈에 첨부

**Comment by sihyung92** [comment]
```
name: backend-dev-analysis

# PR 요청에 대해 
on:
  pull_request:
    branches:
      - develop    # develop 브랜치에서 pr 이벤트가 일어났을 때 실행
    types: [ closed ]    # PR이 closed 됐을 때에만 build 실행

  workflow_dispatch:

defaults:
  run:
    working-directory: ./backend    # build steps의 run을 ./frontend 경로에서 실행

jobs:
  analysis:
    if: (github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.id, 3141722951))
        || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    env:
      SONARQUBE_ID: jujeol-devlop
      SONARQUBE_URL: ${{ secrets.SONARQUBE_URL }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.SUBMODULE_ACCESS_TOKEN }}

      - name: Sonaqube Analysis
        run: ./gradlew test sonarqube
          -Dsonar.host.url=${{ env.SONARQUBE_URL }}
          -Dsonar.projectKey=${{ env.SONARQUBE_ID }}
          -Dsonar.projectName=${{ env.SONARQUBE_ID }}
          -Dsonar.login=${{ secrets.SONARQUBE_ACCESS_TOKEN }}

      - name: Comment Sonarqube URL
        uses: actions/github-script@v4
        with:
          script: |
            const { SONARQUBE_ID, SONARQUBE_URL, PR_NUMBER } = process.env

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `📊 develop 브랜치 코드에 대한 분석결과 확인하기 [링크](${SONARQUBE_URL})`
            })

```

**Comment by sihyung92** [comment]
```
name: backend-build-test
# PR 요청에 대해
on:
  pull_request:
    branches:
      - develop # develop 브랜치에서 pr 이벤트가 일어났을 때 실행
    types: [opened, assigned, synchronize, labeled]
defaults:
  run:
    working-directory: ./backend # build steps의 run을 ./backend 경로에서 실행
jobs:
  build:
    # label이 [backend] (id: 3141722951) 일때만 동작
    if: contains(github.event.pull_request.labels.*.id, 3141722951)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.SUBMODULE_ACCESS_TOKEN }}

      - name: Build Test
        run: ./gradlew bootJar

  analysis:
    if: contains(github.event.pull_request.labels.*.id, 3141722951)
    runs-on: ubuntu-latest
    env:
      SONARQUBE_ID: jujeol-pr
      SONARQUBE_URL: ${{ secrets.SONARQUBE_URL }}
      PR_NUMBER: ${{ github.event.pull_request.number }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.SUBMODULE_ACCESS_TOKEN }}

      - name: Sonaqube Analysis
        run: ./gradlew test sonarqube
             -Dsonar.host.url=${{ env.SONARQUBE_URL }}
             -Dsonar.projectKey=${{ env.SONARQUBE_ID }}
             -Dsonar.projectName=${{ env.SONARQUBE_ID }}-${{ env.PR_NUMBER }}
             -Dsonar.login=${{ secrets.SONARQUBE_ACCESS_TOKEN }}

      - name: Comment Sonarqube URL
        uses: actions/github-script@v4
        with:
          script: |
            const { SONARQUBE_ID, SONARQUBE_URL, PR_NUMBER } = process.env
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `📊 ${ SONARQUBE_ID }-${ PR_NUMBER } 분석 결과 확인하기 [링크](${SONARQUBE_URL})`
            })
```
